# Generated by Django 4.2.3 on 2023-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0005_rename_sales_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='part_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='part_number',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
