# Generated by Django 4.2.3 on 2023-08-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0010_alter_product_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contry_of_origin',
            new_name='country_of_origin',
        ),
    ]
