# Generated by Django 4.2.3 on 2023-08-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0011_rename_contry_of_origin_product_country_of_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='part_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_number',
            new_name='part_number',
        ),
    ]
