# Generated by Django 4.2.3 on 2023-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0015_alter_sparepart_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.IntegerField(default=0),
        ),
    ]
