# Generated by Django 4.2.3 on 2023-08-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0006_sale_part_name_sale_part_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='issued_to',
            new_name='customer_name',
        ),
    ]
