# Generated by Django 4.2.3 on 2023-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0007_rename_issued_to_sale_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
    ]
