# Generated by Django 4.2.3 on 2023-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0008_product_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
