# Generated by Django 4.2.3 on 2023-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0014_rename_item_sale_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
