# Generated by Django 4.2.3 on 2023-08-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0017_remove_sparepart_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='part_number',
            field=models.IntegerField(default=0),
        ),
    ]
