# Generated by Django 4.2.3 on 2023-08-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0018_sparepart_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='part_number',
        ),
    ]
